// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEaIgtiB8VUXbx6KIVkYosK6qElGzhy_4',
    appId: '1:363271052828:web:4d09ac30dcce8c60ed89d9',
    messagingSenderId: '363271052828',
    projectId: 'task-85f1a',
    authDomain: 'task-85f1a.firebaseapp.com',
    databaseURL: 'https://task-85f1a-default-rtdb.firebaseio.com',
    storageBucket: 'task-85f1a.firebasestorage.app',
    measurementId: 'G-K10N0SVB9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimi-nf4mLrmTvy96EFo-1_iw1qfHzSHQ',
    appId: '1:363271052828:android:d2b2082467950d7bed89d9',
    messagingSenderId: '363271052828',
    projectId: 'task-85f1a',
    databaseURL: 'https://task-85f1a-default-rtdb.firebaseio.com',
    storageBucket: 'task-85f1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACJS8o1JYJ2X3PA4792zQx__4XMDTDqwE',
    appId: '1:363271052828:ios:caad7ece58d08f3aed89d9',
    messagingSenderId: '363271052828',
    projectId: 'task-85f1a',
    databaseURL: 'https://task-85f1a-default-rtdb.firebaseio.com',
    storageBucket: 'task-85f1a.firebasestorage.app',
    iosBundleId: 'com.example.jioWorks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACJS8o1JYJ2X3PA4792zQx__4XMDTDqwE',
    appId: '1:363271052828:ios:caad7ece58d08f3aed89d9',
    messagingSenderId: '363271052828',
    projectId: 'task-85f1a',
    databaseURL: 'https://task-85f1a-default-rtdb.firebaseio.com',
    storageBucket: 'task-85f1a.firebasestorage.app',
    iosBundleId: 'com.example.jioWorks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEaIgtiB8VUXbx6KIVkYosK6qElGzhy_4',
    appId: '1:363271052828:web:9550a4812b639b85ed89d9',
    messagingSenderId: '363271052828',
    projectId: 'task-85f1a',
    authDomain: 'task-85f1a.firebaseapp.com',
    databaseURL: 'https://task-85f1a-default-rtdb.firebaseio.com',
    storageBucket: 'task-85f1a.firebasestorage.app',
    measurementId: 'G-YX02ZCHS1P',
  );
}
